[2025-10-07T02:36:50.513+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-07T02:36:50.518+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_forecasting.predict scheduled__2025-10-06T02:30:00+00:00 [queued]>
[2025-10-07T02:36:50.520+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_forecasting.predict scheduled__2025-10-06T02:30:00+00:00 [queued]>
[2025-10-07T02:36:50.520+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-10-07T02:36:50.524+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): predict> on 2025-10-06 02:30:00+00:00
[2025-10-07T02:36:50.528+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=55591) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-07T02:36:50.528+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ml_forecasting', 'predict', 'scheduled__2025-10-06T02:30:00+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/ML Forecast.py', '--cfg-path', '/tmp/tmpbzjhpkx8']
[2025-10-07T02:36:50.530+0000] {standard_task_runner.py:105} INFO - Job 126: Subtask predict
[2025-10-07T02:36:50.530+0000] {standard_task_runner.py:72} INFO - Started process 55594 to run task
[2025-10-07T02:36:50.640+0000] {task_command.py:467} INFO - Running <TaskInstance: ml_forecasting.predict scheduled__2025-10-06T02:30:00+00:00 [running]> on host b99170a1b783
[2025-10-07T02:36:50.662+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ml_forecasting' AIRFLOW_CTX_TASK_ID='predict' AIRFLOW_CTX_EXECUTION_DATE='2025-10-06T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-06T02:30:00+00:00'
[2025-10-07T02:36:50.662+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-07T02:36:50.665+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-10-07T02:36:50.666+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-10-07T02:36:50.666+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-10-07T02:36:50.666+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-10-07T02:37:14.102+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-07T02:37:14.931+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-07T02:37:15.026+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-10-07T02:37:15.027+0000] {connection.py:788} INFO - closed
[2025-10-07T02:37:15.091+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2025-10-07T02:37:15.151+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-07T02:37:15.162+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-07T02:37:15.162+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ml_forecasting, task_id=predict, run_id=scheduled__2025-10-06T02:30:00+00:00, execution_date=20251006T023000, start_date=20251007T023650, end_date=20251007T023715
[2025-10-07T02:37:15.183+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-07T02:37:15.190+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-07T02:37:15.190+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
